### PR TITLE
add multitenancy unregistration

### PR DESCRIPTION
**Pull request by keystroke**
Adds support for unregistering directory tenants which were "onboarded" or "registered" with Azure Stack. The Admin of the onboarded directory tenant runs a cmdlet to uninstall the currently-registered identity applications, and then the Azure Stack Admin runs a cmdlet to disallow authentication within that directory tenant (removes it from the whitelist of allowed directories). If the Admin inadvertently unregisters the directory first, they will have to re-register it before the guest Admin can uninstall the necessary applications. Note that if the guest Admin keeps the permissions.json log file produced when they initially registered (or subsequently ran the registration) they could manually delete the service principals referenced in that file.

### CODE REVIEW

**Comment by keystroke** [comment]
This PR is related to #317.

**Comment by yusukeMatsu** [comment]
https://github.com/keystroke/AzureStack-Tools/blob/5cd6d11b9718084dbd73e5735aefaba07bcedf30/Identity/AzureStack.Identity.psm1#L583-L585

Why is default value of `$ResourceGroupName` `system`? `Register-AzsGuestDirectoryTenant` requests inputting the resource group name of tenant directory to Azure Stack Operator. So the resource group name of tenant directory is not `system`. I think that the param of `$ResourceGroupName` should be `$null` and `Mandatory = $true`.

**Comment by keystroke** [comment]
@yusukeMatsu Good point we should make the resource group parameter mandatory and combine with the fix from PR #396 to create it if it doesn't already exist.

**Comment by keystroke** [comment]
Pushed some fixes to address PR feedback. I also inadvertently ran a linter to format the code so those changes are showing-up as well.

**Comment by yusukeMatsu** [comment]
Great!! I'm looking forward to the next release!

**Pull request merged**
