### PR TITLE
Add MAS-CA01.azurestack.local to the trusted hosts

### PR DESCRIPTION
**Pull request by Pyromaniaxxx**
Add MAS-CA01.azurestack.local to the trusted hosts
- Connect-AzureStackVpn Error Message  
  [mas-ca01.azurestack.local] Connecting to remote server mas-ca01.azurestack.local failed with the following error message : The WinRM client cannot process the request. 
  If the authentication scheme is different from Kerberos, or if the client computer is not joined to a domain, then HTTPS transport must be used or the destination machine must be added to the TrustedHosts configuration setting. Use winrm.cmd to configure TrustedHosts. 
  Note that computers in the TrustedHosts list might not be authenticated.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Pyromaniaxxx__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by Pyromaniaxxx** [comment]
If have multiple subscription
Failure to "Invoke-RestMethod" 
Change to get the "Default Provider Subscription"

-Error Message
Invoke-RestMethod : {"error":{"code":"BadRequest","message":"The subscription identifier 'ba9f6758-be14-4636-b6b8-e677c33e1701 f8443fab-6f96-4006-a9c4-c01f7f8ffd4e' exceeded the 
maximum length of '64' characters."}}
At C:\work\AzureStack-Tools-master\Infrastructure\AzureStack.Infra.psm1:161 char:14

**Comment by igorse** [comment]
Is it safe to run [Set-Item wsman:\localhost\Client\TrustedHosts -Value "MAS-CA01.azurestack.local" -Concatenate] multiple times? May need to test if it has already been added. This script is supposed to be used whenever one needs to connect.

**Comment by Pyromaniaxxx** [comment]
only the first connection
this is not required from the second time

**Pull request closed without merging**
