### PR TITLE
Feature/tenant registration on net core

### PR DESCRIPTION
**Pull request by cblackuk**
In order to allow tenants/users to register with AzureStack using PowerShell Core, we need to change the code as per my commits.

This effectively, checks for Desktop or Core versions of PowerShell and imports AzureRm.Profile module depending on said version.

In addition, Sort command is replaced with Full command Sort-Object to avoid error with Linux using Sort as an integral Linux command.

Furthermore, we are removing/replacing $refreshToken requirement with  -UserCredential; sadly dotnetcore does not pass RefreshToken in $tokens when queried via Graph cmdlets so the only way to authenticate was to use -UserCredential.

Example:
      If ($PSVersionTable.PSEdition -eq "Core") {Initialize-GraphEnvironment -Environment $graphEnvironment -DirectoryTenantId $DirectoryTenantName  -UserCredential (get-credential -Title GlobalAdmin -Message "Enter Your Azure Active Directory Global Admin Credentials")}
        Else {Initialize-GraphEnvironment -Environment $graphEnvironment -DirectoryTenantId $DirectoryTenantName -RefreshToken $refreshToken}

It means that users will have to authenticate twice but at least they can utilise PowerShell Core to perform AzureStack Registration.

Sample run:
docker run -ti azuresdk/azure-powershell-core
```Powershell
PS /> apt-get install git vim -y
PS /> git clone https://github.com/Azure/AzureStack-Tools.git
PS /> vim /AzureStack-Tools/Identity/AzureStack.Identity.psm1
PS /> Import-Module /AzureStack-Tools/Identity/AzureStack.Identity.psm1
PS /> get-module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0        AzureStack.Identity                 {Get-AzsDirectoryTenantidentifier, New-AzsAdGraphServicePrincipal, Register-AzsGuestDirectoryTenant, Register-AzsWithMyDirectoryTenant...}
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty...}
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     1.2        PSReadLine                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PSReadlineKeyHandler, Set-PSReadlineKeyHandler...}


PS /> Register-AzSWithMyDirectoryTenant -TenantResourceManagerEndpoint "https://management.x.x.x.x" -DirectoryTenantName "x.onmicrosoft.com"
VERBOSE: Logging additional information to log file '/AzureStack-Tools/Identity/x.onmicrosoft.com.04-16_13-30-53_3053.log'
Authenticating user...
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXXXX to authenticate.

GlobalAdmin
Enter Your Azure Active Directory Global Admin Credentials
User: admin@x.onmicrosoft.com
Password for user admin@x.onmicrosoft.com: ************

Installing Resource Manager in your directory ('x.onmicrosoft.com')...
Authorizing the Azure PowerShell module to communicate with Resource Manager in your directory...
Acquiring an access token to communicate with Resource Manager... (this may take up to a few minutes to complete)
Looking-up the registered identity applications which need to be installed in your directory...
Installing Application... (1 of 9): xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 'Azure Stack - Hubs'
Installing Application... (2 of 9): xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 'Azure Stack - RBAC'
Installing Application... (3 of 9): xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 'Azure Stack'
Installing Application... (4 of 9): xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 'Azure Stack - Portal'
Installing Application... (5 of 9): xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 'Azure Stack - Policy'
Installing Application... (6 of 9): xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 'Azure Stack - KeyVault'
Installing Application... (7 of 9): xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 'Azure Pack Connector'
Installing Application... (8 of 9): xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 'Azure Stack - Monitoring'
Installing Application... (9 of 9): xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx 'Azure Stack - Compute'


Configuring applications... (this may take up to a few minutes to complete)

All applications installed and configured! Your directory 'mnzxlk.onmicrosoft.com' has been successfully onboarded and can now be used with Azure Stack!

A more detailed description of the applications installed and with what permissions they have been configured can be found in the file '/AzureStack-Tools/Identity/x.onmicrosoft.com.permissions.json'.
Run this script again at any time to check the status of the Azure Stack applications in your directory.
WARNING: If your Azure Stack Administrator installs new services or updates in the future, you may need to run this script again.
```

### CODE REVIEW

**Comment by cblackuk** [comment]
Any chance this can be PRed and merged please?

**Comment by bganapa** [comment]
although it  may work, I do not want to give false impression that the .net core modules would work simply against azure stack. Azure powershell team is coming up with **one version** of AzureRM module based on the .Net Standard which would work against .net core in powershell 6+ as well as .net fx in powershell 5.1+.  We will have support on azurestack based on those modules, till then we should wait

**Comment by cblackuk** [comment]
@bganapa Thanks for taking the time to reply.

Given the fact that registration module is not ported to the actual module and I was told it is not going to be any time soon, by merging this it would allow me to on-board customers to Azure Stack a lot quicker and therefore drive consumption to the platform which in turn bring more revenue to Microsoft.

Is there really nothing we can do?

**Comment by bganapa** [comment]
We should not need this anymore. The az branch is .net core compatible

**Pull request closed without merging**
