### PR TITLE
Update RegisterWithAzure.psm1

### PR DESCRIPTION
**Pull request by leyasa**
Recommend to check for existence of RG prior to creating

### CODE REVIEW

**Comment by bganapa** [comment]
@rakku-ms Coudl you pls review?

**Comment by bganapa** [comment]
@rakku-ms  Do we need this change?

**Comment by vrajasekaran1** [comment]
@rakku-ms Could you please review this PR again?

**Comment by rakku-ms** [comment]
not needed, get-azurermresourcegroup throws error (which will stop the execution) if resource group doesn't exist. new-azurermresourcegroup creates new resource group if one doesn't exists
```
Get-AzureRmResourceGroup : 11:05:33 PM - Provided resource group does not exist.
At line:1 char:1
+ Get-AzureRmResourceGroup -Name "test1"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureRmResourceGroup], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceGroupCmdlet
```

**Comment by rakku-ms** [comment]
closing this old PR

**Pull request closed without merging**
