### PR TITLE
Initial Canary Tests for CLI

### PR DESCRIPTION
**Pull request by viananth**
1)	ServiceAdmin creates quotas, plans, offers and subscription for the tenants – This is done using PowerShell as currently there is no CLI equivalent to this. 
2)	Tenants logs in to his subscription and then creates the resources in CLI – VMs , storage, network, keyvault etc
3) We have adapted Canary powershell script to have consistent tests and results.

### CODE REVIEW

**Comment by bganapa** [comment]
thanks for this work. lets not merge this until we have the CLI released to public

**Comment by vikasnav** [comment]
Can this be merged now?

**Comment by bganapa** [comment]
no need for this to be merged.. we are maintaining it in workloads repo.. lets keep it there only. for outside world , the tests that we are planning to add in CLI repo should be the way forward

**Comment by MatthewMcGlynn** [comment]
This needs to be updated to be comparable with the latest Canary tests - please resubmit a PR once this is updated.

**Pull request closed without merging**
