### PR TITLE
Get-OfferQuota

### PR DESCRIPTION
**Pull request by HassanAlmanasrah**
script to get RPs Quotas assigned to tenants in Azure Stack

### CODE REVIEW

**Comment by vrajasekaran1** [comment]
@rakku-ms can you look this over

**Review by rakku-ms — APPROVED** [review]

**Review by rakku-ms — CHANGES_REQUESTED** [review]
@HassanAlmanasrah can you please put this script under https://github.com/Azure/AzureStack-Tools/tree/az/Support/scripts ?
also, can you please add one example in readme there?

**Comment by HassanAlmanasrah** [comment]
@rakku-ms have created new Pull request https://github.com/Azure/AzureStack-Tools/pull/633 with updating the readme file and placing the script in [https://github.com/Azure/AzureStack-Tools/tree/az/Support/scripts](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FAzureStack-Tools%2Ftree%2Faz%2FSupport%2Fscripts&data=05%7C01%7Chassan.almanasrah%40microsoft.com%7Ccbf3d950b8e145579cec08da847b3d89%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637967962127139321%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HwXa28%2B9V1FytM0pMxsStJIBrbbX%2FJeDVBFsArnud3Q%3D&reserved=0)

**Comment by rakku-ms** [comment]
duplicate of https://github.com/Azure/AzureStack-Tools/pull/633

**Pull request closed without merging**
