### PR TITLE
Update Create-AzSStorageDashboard.ps1

### PR DESCRIPTION
**Pull request by GeorgeH-MS**
Add support of Az module

### CODE REVIEW

**Comment by bganapa** [comment]
@GeorgeH-MS  pls get the appropriate approval and get this merged.  The PR needs to get in to az branch as well

**Comment by GeorgeH-MS** [comment]
@NeilBird @XiangyuKuangMSFT could you help to review this pull request?

**Comment by cblackuk** [comment]
Functionally it is solid, just tested it, but why not just create a separate one for Az and separate for AzureRM (which should be gone very soon anyway) instead of forcing to run the alias command? Though if that is how you would like to to work - it works :-)

**Review by cblackuk — APPROVED** [review]
LGTM

**Comment by bganapa** [comment]
Agree with @cblackuk  here. Can you pls update the az branch for Az powershell usage? This file does not exist in az branch

**Comment by GeorgeH-MS** [comment]
> Agree with @cblackuk here. Can you pls update the az branch for Az powershell usage? This file does not exist in az branch

The pull request https://github.com/Azure/AzureStack-Tools/pull/628 has been created to Az branch. Pls help to check

**Comment by bganapa** [comment]
@NeilBird @XiangyuKuangMSFT  can one of you pls approve this PR?

**Review by NeilBird — APPROVED** [review]
Review Approved.

**Comment by NeilBird** [comment]
@bganapa and @GeorgeH-MS  

I do not have permissions to Merge PRs into this Repo.

**Comment by bganapa** [comment]
Thanks @NeilBird for the review and approval!

**Pull request merged**
