### PR TITLE
Add third party license notice

### PR DESCRIPTION
**Pull request by sethmanheim**

### CODE REVIEW

**Comment by bganapa** [comment]
@sethmanheim is this needed for compliance? Can you pls make a PR to Az branch as well?

**Comment by bganapa** [comment]
Also how is this different from https://github.com/Azure/AzureStack-Tools/blob/master/LICENSE.txt and https://github.com/Azure/AzureStack-Tools/blob/master/ThirdPartyNotices.txt

**Comment by sethmanheim** [comment]
@bganapa This a 3rd party license file for a CSS tool that customers do not have access to, but need to see the third party attributions. We will provide an aka.ms link in the tool for user reference so they can review the file. Does it need to be added to the az branch? Adding @troettinger for approval.

**Comment by bganapa** [comment]
@troettinger  pls review and approve this PR

**Comment by bganapa** [comment]
@sethmanheim  yes, we need this file in az branch as well. at some point of time az branch will become main and master will become azurerm branch. master branch will be kept as such with azurerm to avoid any breaking changes for the customers.

**Review by troettinger — APPROVED** [review]
Thank you for making the agreed changes required for Compute 3rd party tools.

**Pull request merged**
