### PR TITLE
Collect VM Offers and VM Extensions for Publishers

### PR DESCRIPTION
**Pull request by roberto-mardeni**
This fixes issue 214

### CODE REVIEW

**Comment by MatthewMcGlynn** [comment]
@sumantshiv  - please review this and see if it is still needed as a fix. Thanks!

**Comment by shriramnat** [comment]
Hello @roberto-mardeni  , please sign the CLA before we can take a look at the checkin

**Comment by roberto-mardeni** [comment]
Hi @shriramnat, sorry for not attending this at the time needed. Can you please send me instructions on how to sign the CLA for the future, I did not find a contribution guide in this repo.

**Comment by roberto-mardeni** [comment]
Found it, ignore my comments, I will sign the CLA and submit this again.

**Pull request closed without merging**
