### PR TITLE
Fix invalid characters that prevented the prechecker script from running 

### PR DESCRIPTION
**Pull request by dstjacques**

### CODE REVIEW

**Comment by bganapa** [comment]
@dstjacques It is not so visible in the PR differences on what the issue is. Could you pls explain what the change is about? Thanks for the PR!

**Comment by cblackuk** [comment]
Seems like encoding issue/ASCII type whatever type of "-" is being used, so it is replaced with correct one :-)

**Review by cblackuk — APPROVED** [review]
LGTM

**Comment by bjoernf73** [comment]
It is better with an image. The image below shows what is in the original
file. The first error, on line 22, should be "#requires
-runasadministrator".
However, VSCode and the GUIs of Github/Gitlab do not show this for some
reason - but start ISE (Powershell Integrated Script Environment), or any
"stupid" text editor, and open the original file, check line 22. Then open
the same file in this PR, check line 22, and you will see the difference.


[image: image.png]

tir. 7. des. 2021 kl. 21:01 skrev Chris Black ***@***.***>:

**Comment by cblackuk** [comment]
image
vs
image

**Comment by bganapa** [comment]
@bjoernf73 Thanks for the PR and clarification. @cblackuk Thanks for the verification and approval. merging

**Pull request merged**
